### PR TITLE
fix(wakelock_plus): WASM-compatible conditional imports

### PR DESCRIPTION
**Pull request by IchordeDionysos**
## Description

Migrates the conditional imports to support WASM (see https://dart.dev/interop/js-interop/package-web#conditional-imports)

### CODE REVIEW

**Comment by diegotori** [comment]
LGTM. Once it passes automation, I'll merge it in.

If I have time today, I'll publish a new version. Otherwise tomorrow.

**Review by diegotori — APPROVED** [review]
LGTM (contingent on automation passing).

**Comment by IchordeDionysos** [comment]
The failing check seems unrelated to the PR changes 🤔

**Comment by diegotori** [comment]
> The failing check seems unrelated to the PR changes 🤔

Yeah, that happens from time to time. I'll retry it.

Once it goes green, you should be good to go.

**Comment by IchordeDionysos** [comment]
@diegotori nice tests now all passed 💪

**Comment by diegotori** [comment]
@IchordeDionysos thank you for your contribution.

**Pull request merged**
