### PR TITLE
Chore: fix GitHub actions macOS

### PR DESCRIPTION
**Pull request by diegotori**
Added a `brew` workaround due to this [issue](https://github.com/actions/runner-images/issues/8500).

Also added root `.gitignore`.

### CODE REVIEW

**Comment by charleyoliveira** [comment]
Any success here?

**Comment by diegotori** [comment]
It's definitely Github action related.

**Comment by charleyoliveira** [comment]
did you tried with           `brew upgrade python3 || brew link --overwrite python@3.11`

**Comment by diegotori** [comment]
> did you tried with `brew upgrade python3 || brew link --overwrite python@3.11`

I got through that brew hump. However, I also increased the timeout time to 20 minutes, which should be enough to cover the integration tests.

**Pull request merged**
