### PR TITLE
Added conditional export of all 'io' implementations. Addresses issue…

### PR DESCRIPTION
**Pull request by uldall**
Addresses #65

## Description

Only export Linux, MacOS and Windows implementations when not on web.

### CODE REVIEW

**Comment by uldall** [comment]
I am not an export on how the `export` keyword works, so hopefully someone else can determine if this approach is correct.

**Comment by diegotori** [comment]
@uldall Thanks for your contribution. 

This actually works fine because you're properly bucketing `dart:io` usage away from web.

Once the automation passes, then I'll approve.

**Review by diegotori — APPROVED** [review]
LGTM.

**Comment by diegotori** [comment]
@uldall since it's the fourth of July holiday weekend here in the States, the earliest that this will get deployed is on Monday. 

Thanks for your contribution.

**Comment by uldall** [comment]
> @uldall since it's the fourth of July holiday weekend here in the States, the earliest that this will get deployed is on Monday.
> 
> Thanks for your contribution.

No problem, thank you for taking your time to look into this :)

**Comment by uldall** [comment]
Hi @diegotori, would it possible to get this merged and released? Then I wouldn't have to keep a separate build which would be quite nice :) Thank you in advance!

**Comment by diegotori** [comment]
@uldall sure. Lemme just merge it first. In the meantime, override the dependency so that it gets it from git main

**Comment by diegotori** [comment]
@uldall released as part of version `1.2.6`. Once again, thanks for your contribution.

**Pull request merged**
