### PR TITLE
Allow use package_info_plus 5.x.x

### PR DESCRIPTION
**Pull request by dkrutskikh**
## Description

Allow to resolve package_info_plus 5.x.x

### CODE REVIEW

**Comment by diegotori** [comment]
LGTM. Please re-sync your branch with `main`. Thanks.

**Comment by diegotori** [comment]
@dkrutskikh once your branch is re-synced with `main`'s latest changes and it passes all of the GitHub Actions, then I'll merge and release. Thanks.

**Comment by dkrutskikh** [comment]
@diegotori done

**Comment by diegotori** [comment]
Merged. Will be released later today. Thanks for your contribution.

**Pull request merged**
