### PR TITLE
Upgrade package_info_plus range to ">=4.0.2 <=6.0.0"

### PR DESCRIPTION
**Pull request by CarloDotLog**
## Description

This PR upgrades the `package_info_plus` package range to  `">=4.0.2 <=6.0.0"` to support the version `6.0.0` of `package_info_plus`.

#30

### CODE REVIEW

**Comment by diegotori** [comment]
Thank you for the submission. I'll review it on Monday

**Comment by arabnology** [comment]
When the update ?! we are waiting as it is very important for us.

**Comment by ycv005** [comment]
yes, please update, facing issue while upgrade other package.

**Comment by diegotori** [comment]
Closing your PR in favor of #33. Thanks for your contribution.

**Pull request closed without merging**
