### PR TITLE
chore: loosen dependency constraint to support package_info_plus v8 and v9

### PR DESCRIPTION
**Pull request by josxha**
### Changes
This pull request loosens the constraint to support v6, v7 and v8 of `package_info_plus`.

- fix https://github.com/fluttercommunity/wakelock_plus/issues/50
- replaces https://github.com/fluttercommunity/wakelock_plus/pull/51 since it only allows version 8.0.0 of `package_info_plus` and not all minor and patch versions (8.x.x).

### Description
The latest version of package_info_plus is 8.0.0 while the constraint in wakelock_plus is set to <8.0.0. 
There is only one breaking change in package_info_plus that wakelock_plus:
```yaml
BREAKING FEAT(package_info_plus): Switch to SHA-256 for buildSignature on Android
```

`package_info_plus` isn't affected by this breaking change because the only usage is `appName` in `wakelock_plus_linux_plugin.dart`.

### CODE REVIEW

**Review by dbebawy-modus — APPROVED** [review]

**Comment by diegotori** [comment]
@josxha thanks for your PR. Once the tests go green, then I'll approve. 

Since I'm currently out of the country, I'll be able to deploy a new build on Tuesday the earliest. 

In the meantime, you can add a dependency override to this new package_info_plus version in your pubspec.

**Comment by josxha** [comment]
Thanks for your response @diegotori! I tried to look into the failed CI. I don't think that there isn't really a problem and they just ran into a timeout that one time.
Althrough, I can't really debug the workflows while they need manual approval to run. But all tests went trhough successfully when I triggered them [in my fork](https://github.com/josxha/wakelock_plus/pull/1).

**Comment by mrwebbeast** [comment]
Hi Guys any updates on this

**Review by diegotori — APPROVED** [review]
LGTM.

**Pull request merged**
